# @format

project:
  title: "boxplot"

format:
  html:
    toc: true
    theme:
      light: cosmo # cerulean lumen flatly
      dark: cyborg
    number-sections: false
    embed-resources: false
  # pdf:
  #   toc: false
execute:
  freeze: auto
